# Heavily aided by: https://gist.github.com/brenns10/f48e1021e8befd2221a2
language: python
python:
  - 3.8
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
install:
  # travis_wait needed to avoid overflowing log, remove it to debug
  - travis_wait pip install pipenv --verbose
  - travis_wait pipenv install --dev --verbose
  - gem install html-proofer
script:
  - cd form_submit/templates/docs
  - pipenv run make html
  - pipenv run make doctest
  # Require a link check to work to pass a PR.
  - if $TRAVIS_PULL_REQUEST; then htmlproofer _build/html --allow_hash_href --file_ignore "_build/html/search.html" --url-ignore https://rawgit.com/AguaClara/aide_design_specs/test/html/index.html; fi;
after_script:
  - htmlproofer _build/html --allow_hash_href --file_ignore "_build/html/search.html" --url-ignore https://rawgit.com/AguaClara/aide_design_specs/test/html/index.html
